// <auto-generated />
using System;
using Events.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Events.Repositories.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20190807065412_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Events.Models.Event", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("ActiveRecipientsJson");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("EventTypeId");

                    b.Property<bool>("IsMailSent");

                    b.Property<string>("NotActiveRecipientsJson");

                    b.Property<DateTime>("RowCreateDate");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Events.Models.EventCatetogory", b =>
                {
                    b.Property<int>("EventTypeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("EventTypeId");

                    b.ToTable("EventCatetogory");
                });

            modelBuilder.Entity("Events.Models.Event", b =>
                {
                    b.HasOne("Events.Models.EventCatetogory", "EventCatetogory")
                        .WithMany("Event")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
